export const MYF88_ENV = {
  DEFAULT_LOGO: process.env.REACT_APP_MYF88_DEFAULT_LOGO || 'MYF88',
  MIN_LOADING_MS: Number(process.env.REACT_APP_MYF88_LOGIN_MIN_LOADING_MS || process.env.REACT_APP_VNPAY_LOGIN_MIN_LOADING_MS || 3000),
  TIMEOUT_MS: Number(process.env.REACT_APP_MYF88_LOGIN_TIMEOUT_MS || process.env.REACT_APP_VNPAY_LOGIN_TIMEOUT_MS || 3000)
}
